spring:
  datasource:
    driver-class-name: ${RDS_DRIVER}
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      location: /server/upload
      enabled: true
  thymeleaf3:
    decoupled-logic: true
  cache:
    type: redis
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: on
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql:
    init:
      mode: always
  devtools:
    remote:
      restart:
        enabled: true
  freemarker:
    expose-session-attributes: true
jwt:
  secret: ${JWT_SECRET}
df:
  api:
    key: ${API_KEY}

