spring:
  profiles:
    active: dev

debug: false
jwt:
  secret: ${JWT_SECRET}
df:
  api:
    key: ${API_KEY}
management.endpoints.web.exposure.include: "*"
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

