spring:
  profiles:
    active: dev

debug: false
jwt:
  secret: ${JWT_SECRET}
df:
  api:
    key: ${API_KEY}
management.endpoints.web.exposure.include: "*"
oauth:
  kakao:
    client-id: e73c04042b70c7c3dbea595a140c8221
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  google:
    client-id: 1087942298436-psejomddf9lap0hjuvqfqkei0h14ubjk.apps.googleusercontent.com
    url:
      client-secret: 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
      redirect-uri: http://localhost:3000/users/google
      token-uri: 엑세스토큰URI
      resource-uri: 리소스URI

