insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_0.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_1.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_2.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_3.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_4.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_5.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_6.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_7.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_8.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_9.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_10.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_11.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_12.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_13.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_14.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');
insert into SAVE_FILE (FILE_NAME,FILE_PATH,FILE_SIZE,FILE_TYPE,CREATED_AT,CREATED_BY,MODIFIED_AT,MODIFIED_BY) values ('icon_char_15.png','/Users/brinc/Desktop/brincestudy/JAVA/df-toy-project/src/main/resources/static/images/icon_char/','0','.png',now(),'brinc',now(),'brinc');

insert into USER_ACCOUNT (USER_ID, CREATED_AT, CREATED_BY, MODIFIED_AT, MODIFIED_BY, EMAIL, NICKNAME, PASSWORD,PROFILE_IMG_ID) VALUES ( 'test',now(),'test',now(),'test','test@email.com','test','$2a$10$DAd.J6N1fv8ecD0UsYKOu.yPnrAQe.lw4pJmLaX6d3fhJ5Bzllw5.', 1 );
insert into USER_ACCOUNT_ROLES (USER_ACCOUNT_USER_ID, ROLES) VALUES ( 'test','ROLE_USER' );

